def exception(retcode):
    exceptions = {
        10004: "Requote",
        10006: "Request rejected",
        10007: "Request canceled by trader",
        10008: "Order placed",
        10009: "Request completed",
        10010: "Only part of the request was completed",
        10011: "Request processing error",
        10012: "Request canceled by timeout",
        10013: "Invalid request",
        10014: "Invalid volume in the request",
        10015: "Invalid price in the request",
        10016: "Invalid stops in the request",
        10017: "Trade is disabled",
        10018: "Market is closed",
        10019: "There is not enough money to complete the request",
        10020: "Prices changed",
        10021: "There are no quotes to process the request",
        10022: "Invalid order expiration date in the request",
        10023: "Order state changed",
        10024: "Too frequent requests",
        10025: "No changes in request",
        10026: "Autotrading disabled by server",
        10027: "Autotrading disabled by client terminal",
        10028: "Request locked for processing",
        10029: "Order or position frozen",
        10030: "Invalid order filling type",
        10031: "No connection with the trade server",
        10032: "Operation is allowed only for live accounts",
        10033: "The number of pending orders has reached the limit",
        10034: "The volume of orders and positions for the symbol has reached the limit",
        10035: "correct or prohibited order type",
        10036: "Position with the specified POSITION_IDENTIFIER has already been closed",
        10038: "A close volume exceeds the current position volume",
        10039: "A close order already exists for a specified position",
        10040: "The number of open positions simultaneously present on an account can be limited by the server settings.",
        10041: "The pending order activation request is rejected, the order is canceled",
        10042: "The request is rejected, because the Only long positions are allowed rule is set for the symbol (POSITION_TYPE_BUY)",
        10043: "The request is rejected, because the Only short positions are allowed rule is set for the symbol (POSITION_TYPE_SELL)",
        10044: "The request is rejected, because the Only position closing is allowed rule is set for the symbol",
        10045: "The request is rejected, because Position closing is allowed only by FIFO rule flag is set for the trading account (ACCOUNT_FIFO_CLOSE=true)",
        10046: "The request is rejected, because the Opposite positions on a single symbol are disabled rule is set for the trading account"
        
    }
    return exceptions.get(retcode)
    
